### ISSUE TITLE
No such file or directory: 'temp_ils/temp_0.phy'

### ISSUE THREAD

**Issue by NaKent** [meganlsmith/phyloGAN#1]
Thank you for developing an interesting way of building phylogenetic tree.
I tried to make use of phyloGAN with provided test data along with readme.md, but following error was shown and the run could't be completed.

---
STAGE 1: Infer LAMBDA.

 ITER 0

time 17:25:36.909103
Traceback (most recent call last):
  File "./phyloGAN_ils/scripts/phyloGAN.py", line 96, in <module>
    main()
  File "./phyloGAN_ils/scripts/phyloGAN.py", line 34, in main
    estimated_scale, estimated_coal = my_phylogan.stage1(Min_scale = parameters['Min_scale'], Max_scale = parameters['Max_scale'],
  File "/home/kent/phyloGAN/phyloGAN_ils/scripts/phylogan_architecture.py", line 84, in stage1
    proposed_dist = Stage1_Trainer.simple_loss_stage1(proposed_scale, proposed_coal)
  File "/home/kent/phyloGAN/phyloGAN_ils/scripts/training.py", line 29, in simple_loss_stage1
    simulated_data, empirical_samples = self.Simulator.simulateScaleCoal(current_scale, current_coal)
  File "/home/kent/phyloGAN/phyloGAN_ils/scripts/simulators.py", line 69, in simulateScaleCoal
    char_matrix = dendropy.DnaCharacterMatrix.concatenate_from_paths(paths=path_list, schema="phylip")
  File "/home/kent/.local/lib/python3.8/site-packages/dendropy/datamodel/charmatrixmodel.py", line 678, in concatenate_from_paths
    streams = [open(path, "rU") for path in paths]
  File "/home/kent/.local/lib/python3.8/site-packages/dendropy/datamodel/charmatrixmodel.py", line 678, in <listcomp>
    streams = [open(path, "rU") for path in paths]
FileNotFoundError: [Errno 2] No such file or directory: 'temp_ils/temp_0.phy'

**Comment by meganlsmith** [comment]
Hi Mori,

Thanks!

It looks like the phylip file is not being generated appropriately during simulations. Can you verify that you are using the correct path to your copy of IQTree in the parameters file, and that it is version >= 2.2.0?

Also, depending on your reason for running phyloGAN, you might want to consider starting with the non-ILS version. It is a lot faster, and we were able to run it on more taxa. 

Let me know if the problem persists!

Best,
Megan

**Comment by NaKent** [comment]
Thank you for answering my basic questions.
I had forgotten to change the path to the IQ-TREE parameter file :(

Best regards,
Mori
